### ISSUE TITLE
안심존 실험 #1 : checklist

### ISSUE THREAD

**Issue by yjyjyjcho** [NIA-Adp-Healthcare/2020-02-013-042#2]
##실험 index

- [x] code clone
- [ ] model clone
- [ ] env(lib, package) clone
- [ ] modeling : US_AI_model
- [ ] modeling : UNET
- [ ] EDA : ref. Kaggle data

* File system
- [ ] 각 file 내 이미지 data 일괄 폴더 이동
- [ ] file 명 일괄 변경
